# Generated by Django 3.2.9 on 2021-11-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emobot', '0002_auto_20211116_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
