# Generated by Django 3.2.7 on 2022-02-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emobot', '0004_auto_20220203_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotiontable',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emobot.person'),
            preserve_default=False,
        ),
    ]
